apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openbalena.vpn.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.vpn.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openbalena.vpn.selectorLabels" . | nindent 6 }}
  {{- if .Values.vpn.replicas }}
  replicas: {{ .Values.vpn.replicas }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "openbalena.vpn.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-vpn
          image: "{{ .Values.vpn.image.repository }}:{{ .Values.vpn.image.tag }}"
          {{- if .Values.vpn.image.pullPolicy }}
          imagePullPolicy: {{ .Values.vpn.image.pullPolicy }}
          {{- end }}
          {{- with .Values.vpn.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - mountPath: /run
            name: run
          - mountPath: /sys/fs/cgroup
            name: cgroup
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN", "SYS_RESOURCE", "NET_ADMIN"]
          env:
          - name: CONFD_BACKEND
            value: "ENV"
          {{- with .Values.vpn.env }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      volumes:
      - name: run
        emptyDir:
          medium: Memory
      - name: cgroup
        emptyDir:
          medium: Memory
      {{- with .Values.vpn.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vpn.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vpn.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
