{{- if .Values.issuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: {{ .Values.issuer.server }}
    {{- if .Values.issuer.preferredChain }}
    preferredChain: {{ .Values.issuer.preferredChain }}
    {{- end }}
    {{- with .Values.issuer.externalAccountBinding }}
    externalAccountBinding:
      {{ toYaml . | indent 8 }}
    {{- end }}
    privateKeySecretRef:
      name: {{ .Values.issuer.secretName }}
    {{- with .Values.issuer.solvers  }}
    solvers:
      {{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
