apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openbalena.redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    matchLabels:
      {{- include "openbalena.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  serviceName: {{ include "openbalena.redis.fullname" . }}
  {{- if .Values.redis.replicas }}
  replicas: {{ .Values.redis.replicas }}
  {{- end }}
  {{- if .Values.redis.podManagementPolicy }}
  podManagementPolicy: {{ .Values.redis.podManagementPolicy }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "openbalena.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      {{- if .Values.redis.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.redis.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        {{- with .Values.redis.ports }}
        ports:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      {{- if .Values.redis.storageClassName }}
      storageClassName: {{ .Values.redis.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.redis.storage }}
