apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openbalena.s3.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.s3.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openbalena.s3.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "openbalena.s3.fullname" . }}
  {{- if .Values.s3.replicas }}
  replicas: {{ .Values.s3.replicas }}
  {{- end }}
  {{- if .Values.s3.podManagementPolicy }}
  podManagementPolicy: {{ .Values.s3.podManagementPolicy }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "openbalena.s3.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.s3.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.s3.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-s3
        image: "{{ .Values.s3.image.repository }}:{{ .Values.s3.image.tag }}"
        {{- with .Values.s3.ports }}
        ports:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: s3-export
          mountPath: /export
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_RESOURCE"]
        env:
        - name: CONFD_BACKEND
          value: "ENV"
        {{- with .Values.s3.env }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: s3-export
    spec:
      accessModes: ["ReadWriteOnce"]
      {{- if .Values.s3.storageClassName }}
      storageClassName: {{ .Values.s3.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.s3.storage }}
