apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbalena.db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.db.labels" . | nindent 4 }}
  {{- with .Values.db.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "openbalena.db.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.db.service.ports }}
    - port: {{ .port }}
      {{- if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- end }}
      {{- if .protocol }}
      protocol: {{ .protocol }}
      {{- end }}
      {{- if .name }}
      name: {{ .name }}
      {{- end }}
    {{- end }}
  {{- with .Values.db.service.externalIPs }}
  externalIPs:
    {{- toYaml . | indent 4 }}
  {{- end }}
